### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/ISAAKiel.github.io#4]
I don't like the background image in the header. 

![header_bg](https://user-images.githubusercontent.com/10789038/29265086-017bbdd0-80e0-11e7-86e0-01f8534d2576.jpg)

Any ideas for better images? Photos? Graphs? Screenshots? Collages?

@MartinHinz Could we manage the transparent blue overlay via CSS? Then we don't have to provide a replacement image with this setting.

**Comment by quassinja** [comment]
I could offer one of my pictures of some agent based modelling in a
neoassyrian palace as part of a collage or replacement. Maybe not the whole
picture but a part of it.

Das sollte auch mit einem transparent baluen overlay noch ok aussehen :)

2017-08-14 11:08 GMT+02:00 Clemens Schmid <notifications@github.com>:

**Comment by quassinja** [comment]
![agents_palace](https://user-images.githubusercontent.com/24542470/29670618-7dcdf6c8-88e7-11e7-80e3-fd91d2450196.png)

Würde einen Ausschnitt von dem Bild natürlich wählen wenn

**Comment by nevrome** [comment]
![52a](https://user-images.githubusercontent.com/10789038/29692362-e29cbf06-892f-11e7-817f-0db7af81b467.jpg)

**Comment by MartinHinz** [comment]
@nevrome Would not do a transparent overlay, additional possibility for browser incompatibility... Better server a blueish image.

**Comment by nevrome** [comment]
@MartinHinz K - it's no problem to prepare the picture with the overlay.

**Comment by MartinHinz** [comment]
![homepage_banner](https://user-images.githubusercontent.com/3285169/29718309-97d2df72-89b2-11e7-9cf1-d66562c46609.jpg)

**Comment by MartinHinz** [comment]
Could probably be more blueish

**Comment by nevrome** [comment]
Cool! Can we get a monochrome below the blue layer version?

**Comment by MartinHinz** [comment]
![homepage_banner_bw_back](https://user-images.githubusercontent.com/3285169/29718625-b24754f4-89b3-11e7-8bb0-2f48ea2b251d.jpg)

**Comment by MartinHinz** [comment]
Here you go...
